### ISSUE TITLE
How to run comp_plan and create my own environment

### ISSUE THREAD

**Issue by OAHC2022** [devinluo27/potential-motion-plan-release#1]
Thank you for your work. I am currently experimenting with the composability of diffusion models for Maze2D and encountered some issues with getting `comp_plan_rm2d.py` to work. I tried running both `comp_plan_rm2d.sh` and `comp_plan_rm2d_list.sh`, but I encountered the following error: 
```bash
comp_plan_rm2d.py: error: the following arguments are required: --dataset
```
I am unsure of what to provide for the `--dataset` argument.

Additionally, I would like to create my own Maze2D environment to test the composability of the diffusion model. Could you please provide some guidance on how to achieve this? Thank you!

**Comment by devinluo27** [comment]
Thank you for bringing it to notice. 

The `--dataset` argument is actually redundant, since we already define the `dataset` in the config file.  Therefore, you can just remove this [line](https://github.com/devinluo27/potential-motion-plan-release/blob/4f35d2884e57c9148662b7ec175db0b7c694f661/scripts/comp/comp_plan_rm2d.py#L19).

To create your own composed Maze2D environments, you might want to start from [here](https://github.com/devinluo27/potential-motion-plan-release/blob/4f35d2884e57c9148662b7ec175db0b7c694f661/pb_diff_envs/pb_diff_envs/environment/init_maze2d_gym.py#L394), where we construct a composed environment with 6+5 obstacles. You might also want to go through the evaluation pipeline starting from `comp_plan_rm2d.py`.

**Comment by OAHC2022** [comment]
Thank you for your quick response! I was able to get `comp_plan_rm2d.sh` working, and now I’m planning to look into how to create my own composed Maze2D environments.
